[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/healthz"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.envs]
NODE_ENV = "production" 